### ISSUE TITLE
Execute Pynisher without limitations

### ISSUE THREAD

**Issue by renesass** [automl/pynisher#19]
Does that makes sense?

**Comment by mfeurer** [comment]
Yes, that would make sense. Users from time to time want to disable the limitations pynisher enforces.

**Comment by eddiebergman** [comment]
This can already be done, however it will still spawn things in a new process to keep behaviour consistent with respect to error handling and anything else that gets done.

I don't think it makes sense for pynisher to secretly run it in the same process (as discussed with rene) due to this behaviour change which would make pynisher operator in two different ways.

As this can easily be controlled done by the consumer of pynisher, i.e. they can decide if they want pynisher to handle it or just run it in same process if there's no limits, I will close this issue.
